---
title: "Lesson Plan"
output: html_document
date: "2023-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ground Rules

-   Assume 15 minutes for intro / icebreaker

-   Assume 15 minutes for capstone exercise + Review (Outro)

-   Aim for 5 minutes talking + 5 minutes activity for each 'topic'

-   10 minute break every hour

-   Therefore, about 2 hours of "topics" (+10 minute buffer)

    -   10 minutes each (5 minutes talking + 5 minutes activity)

    -   = **12 topics**

## Outline

0.  Intro: Tidyverse overview
1.  Load data: readr
    1.  Working directory & paths
    2.  read_csv, readLines
    3.  skip argument
2.  Explore data (base)
    1.  data.frames & tibbles (review)
    2.  Explore (base)
        1.  head(), dims(), names(), str(), etc.
    3.  Know your data: CO2
    4.  **Activity 1: Find the issues** [with a script? optional]
3.  Scripts
    1.  Make a simple script
    2.  *Comments [the sooner this gets introduced, the sooner I can use them in examples! And they get included in output script]*
    3.  **Activity 2 (short): add your favourite exploring commands from the previous activity to your script.**
    4.  Housekeeping: rm(list=ls())
    5.  open a script for the workshop code
    6.  Run code from the script.
4.  correct some issues by re-loading with options
    1.  encoding (more in extras)
        1.  **Mini-Activity: Read latin1-encoded file and look at the difference**
    2.  names
    3.  column types
    4.  missing values?
    5.  locale: grouping_mark (for commas) [or just clean by /10 whenever \>100]
    6.  *'Final' Load: one version for the rest of the workshop.*
    7.  **Activity 3: readxl** in a script [need info on options, check results]
5.  Explore with dplyr: select() & filter() parts of a data frame
    1.  dplyr intro & overview
        1.  load dplyr
            1.  ~~package::function notation?~~ (extras)
        2.  *dplyr conventions?*
    2.  select()
    3.  selection helpers
    4.  ***Activity ?: select()***
    5.  filter()
    6.  **Activity 4: filter()**
    7.  pipes
    8.  **Activity 5 (short): convert expressions to pipes**
    9.  *dplyr conventions (after seeing a couple of examples, and pipes)?*
6.  Find specific values in example data
    1.  ID character columns where numeric expected
    2.  Locate non-numeric values in character column
    3.  unusual numeric values
    4.  ***Activity ?**[can be included in other activities, too]*
    5.  ~~Find issues systematically~~ (move to Extras)
        1.  ~~for loops? [need scripts]~~
            1.  *makes less sense if using read_csv() version: only 1 character column*
7.  Manipulate Data
    1.  mutate()
    2.  mutate() helper functions
    3.  *select vs mutate semantics*
    4.  **Activity 6: use mutate() on tidy data** [ ~~CO2~~, iris ]
8.  Conditional execution
    1.  ***if () else () -\> if_else(), case_when()***
    2.  **Activity 7: practice using mutate with conditions** on `iris` dataset
9.  stringr + mutate: clean character columns
    1.  clean columns in example data

    2.  stringr example: str_replace() ?

    3.  package:: object notation to use tidyr::fill()

    4.  **Activity 8: modify some strings (script)**
10. Grouped data
    1.  group_by()
    2.  summarize()
    3.  **Activity 9: summarize CO2 vs loaded (wide) data**
        1.  source() external script to generate `CO2_wide`
        2.  Exposure to different layouts
    4.  Clean rows in *example data*?
        1.  Laborious to summarize() multiple columns; would be easier if 1 column ...
11. tidyr
    1.  tidy data
    2.  missing values?
    3.  unite
    4.  *pivot*
    5.  Tidy *example data*
        1.  Finish cleaning by removing duplicates with summarize()
    6.  **Activity 10: pivot_wider & back** [with CO2]
12. Save data
    1.  **Activity 11:** split CO2 data by a Type or Treatment & save to separate files?
        1.  for loops optional
13. Combining tables
    1.  bind_rows() & bind_cols()
    2.  mention joins, but no time for examples (extras?)
    3.  **Activity 12: split & recombine CO2 dataset** (read files saved in last activity?)
        -   summarize() a dataset and merge back with original for calculation?
        -   or just group_by() & mutate()

------------------------------------------------------------------------

1.  *Code Style*
    1.  Notebooks?
2.  **Capstone Activity**
    1.  load, check, clean multiple files [4x subsets of who dataset]
    2.  *Combine into larger file*
    3.  Answer simple analysis question / calculation
    4.  Optional: work in pairs to separate tasks
3.  Review
    0.  other packages for other formats & data types

### Missing Topics

-   comparing NAs

-   Programming:

    -   ~~functions (introduce just before ad hoc functions?)~~

        -   variable scope

        -   custom messages, warnings, errors?

        -   **ad hoc functions**

    -   loops: for [short intro for capstone exercise?]

    -   Could build this into visualization: might be more natural, more time for it?

-   2-table verbs (join) --- NO TIME!

    -   Combine 2 tables: at least bind_rows, bind_cols

    -   No time for join

-   factors

-   sort: arrange()

    -   leave to explore on their own

# Notes from previous events of this workshop

-   Some had real difficulty downloading, finding files & following along with the script file at first.

    -   Assistants to help people 1-on-1?

    -   Spend *more* time ensuring people are setup with all the files locally at the beginning, or send more instructions of what to do.

-   Skip file path format (move to Extras): simplify people's lives and stick to forward slash or file.path()?

-   OR change approach to not use local files and read all files from remote URL?

    -   Might not work if in-person & offline ...
    -   Avoids struggles with relative paths.

-   Too fast, too much.

    -   Refocus again, reduce ambitious goals.
    -   write() functions sooner to get them out of the way?
    -   Have dedicated section on cleaning the example file (so sections stand alone more?)

-   1 hr: only at Activity 2?

-   2 hrs: finished Activity 5

-   2.5 hrs: Activity 7 (mutate + conditions)

-   Some still needing time to understand how to apply functions.

-   Many asked for example solutions for the activities.

-   Skipped stringr activity

-   Last activity was the one for summarize()

-   No time to finish cleaning example data

-   Quick overview of Tidy

-   Skipped 2-table verbs & final activity entirely

-   Ended 5-6 minutes over time, mostly reviewing Pop Quiz.
